import Foundation

// MARK: - CharMapLetters

/// 5×7 pixel font bitmaps for uppercase letters A-Z and common symbols.
/// Each character is stored as a 7-row × 5-column [[Bool]] matrix.
/// Row 0 is the visual top of the character.
enum CharMapLetters {
    static let map: [Character: [[Bool]]] = [
        // MARK: A-Z
        "A": [
            [false, true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  true,  true,  true,  true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
        ],
        "B": [
            [true,  true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  true,  true,  true,  false],
        ],
        "C": [
            [false, true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, true ],
            [false, true,  true,  true,  false],
        ],
        "D": [
            [true,  true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  true,  true,  true,  false],
        ],
        "E": [
            [true,  true,  true,  true,  true ],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  true,  true,  true,  false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  true,  true,  true,  true ],
        ],
        "F": [
            [true,  true,  true,  true,  true ],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  true,  true,  true,  false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
        ],
        "G": [
            [false, true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, false],
            [true,  false, false, true,  true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [false, true,  true,  true,  false],
        ],
        "H": [
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  true,  true,  true,  true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
        ],
        "I": [
            [false, true,  true,  true,  false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, true,  true,  true,  false],
        ],
        "J": [
            [false, false, false, false, true ],
            [false, false, false, false, true ],
            [false, false, false, false, true ],
            [false, false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [false, true,  true,  true,  false],
        ],
        "K": [
            [true,  false, false, false, true ],
            [true,  false, false, true,  false],
            [true,  false, true,  false, false],
            [true,  true,  false, false, false],
            [true,  false, true,  false, false],
            [true,  false, false, true,  false],
            [true,  false, false, false, true ],
        ],
        "L": [
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  true,  true,  true,  true ],
        ],
        "M": [
            [true,  false, false, false, true ],
            [true,  true,  false, true,  true ],
            [true,  false, true,  false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
        ],
        "N": [
            [true,  false, false, false, true ],
            [true,  true,  false, false, true ],
            [true,  false, true,  false, true ],
            [true,  false, false, true,  true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
        ],
        "O": [
            [false, true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [false, true,  true,  true,  false],
        ],
        "P": [
            [true,  true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  true,  true,  true,  false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
        ],
        "Q": [
            [false, true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, true,  false, true ],
            [true,  false, false, true,  false],
            [false, true,  true,  false, true ],
        ],
        "R": [
            [true,  true,  true,  true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  true,  true,  true,  false],
            [true,  false, true,  false, false],
            [true,  false, false, true,  false],
            [true,  false, false, false, true ],
        ],
        "S": [
            [false, true,  true,  true,  true ],
            [true,  false, false, false, false],
            [true,  false, false, false, false],
            [false, true,  true,  true,  false],
            [false, false, false, false, true ],
            [false, false, false, false, true ],
            [true,  true,  true,  true,  false],
        ],
        "T": [
            [true,  true,  true,  true,  true ],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
        ],
        "U": [
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [false, true,  true,  true,  false],
        ],
        "V": [
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [false, true,  false, true,  false],
            [false, false, true,  false, false],
        ],
        "W": [
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [true,  false, true,  false, true ],
            [true,  false, true,  false, true ],
            [true,  true,  false, true,  true ],
            [true,  false, false, false, true ],
        ],
        "X": [
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [false, true,  false, true,  false],
            [false, false, true,  false, false],
            [false, true,  false, true,  false],
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
        ],
        "Y": [
            [true,  false, false, false, true ],
            [true,  false, false, false, true ],
            [false, true,  false, true,  false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
        ],
        "Z": [
            [true,  true,  true,  true,  true ],
            [false, false, false, false, true ],
            [false, false, false, true,  false],
            [false, false, true,  false, false],
            [false, true,  false, false, false],
            [true,  false, false, false, false],
            [true,  true,  true,  true,  true ],
        ],
        // MARK: Symbols
        "%": [
            [true,  true,  false, false, true ],
            [true,  true,  false, true,  false],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
            [false, true,  false, false, false],
            [true,  false, false, true,  true ],
            [true,  false, false, true,  true ],
        ],
        "¥": [
            [true,  false, false, false, true ],
            [false, true,  false, true,  false],
            [true,  true,  true,  true,  true ],
            [false, false, true,  false, false],
            [true,  true,  true,  true,  true ],
            [false, false, true,  false, false],
            [false, false, true,  false, false],
        ],
        "$": [
            [false, false, true,  false, false],
            [false, true,  true,  true,  false],
            [true,  false, true,  false, false],
            [false, true,  true,  true,  false],
            [false, false, true,  false, true ],
            [false, true,  true,  true,  false],
            [false, false, true,  false, false],
        ],
        ".": [
            [false, false, false, false, false],
            [false, false, false, false, false],
            [false, false, false, false, false],
            [false, false, false, false, false],
            [false, false, false, false, false],
            [false, false, false, false, false],
            [false, false, true,  false, false],
        ],
        "?": [
            [false, true,  true,  true,  false],
            [true,  false, false, false, true ],
            [false, false, false, false, true ],
            [false, false, false, true,  false],
            [false, false, true,  false, false],
            [false, false, false, false, false],
            [false, false, true,  false, false],
        ],
        "\u{2022}": [ // Bullet •
            [false, false, false, false, false],
            [false, false, false, false, false],
            [false, false, true,  false, false],
            [false, true,  true,  true,  false],
            [false, false, true,  false, false],
            [false, false, false, false, false],
            [false, false, false, false, false],
        ],
        "/": [
            [false, false, false, false, true ],
            [false, false, false, false, true ],
            [false, false, false, true,  false],
            [false, false, true,  false, false],
            [false, true,  false, false, false],
            [true,  false, false, false, false],
            [false, false, false, false, false],
        ],
    ]
}
